# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: vwm
      MONGO_INITDB_ROOT_PASSWORD: vwm
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vwm
      ME_CONFIG_MONGODB_ADMINPASSWORD: vwm
